
services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./server
    restart: always
    env_file:
      - .env
    volumes:
      - static_volume:/server/static
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  frontend:
    build: ./client
    restart: always
    ports: 
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume: